os:
  - osx

language: java

before_install:
  - brew update
  - npm install --global surge
  - wget https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
  - hdiutil attach googlechrome.dmg
  - cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
install:
  - brew cask install chromedriver
  - brew install gauge
  - gauge install java
  - gauge install html-report
  - gauge install screenshot
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean
  - mvn test

deploy:
  provider: surge
  project: ./reports/html-report/
  domain: innocent-trip.surge.sh
  skip_cleanup: false
