os:
  - osx

language: java

before_install:
  - brew update
  - npm install --global surge

install:
  - brew cask install google-chrome
  - brew cask install chromedriver
  - brew install gauge
  - gauge install java
  - gauge install html-report
  - gauge install screenshot
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean
  - mvn test

deploy:
  provider: surge
  project: ./reports/html-report/
  domain: innocent-trip.surge.sh
  skip_cleanup: false
